---
output: 
  bookdown::html_document2:
    code_folding: hide
---

# Exploration of DA Bight dataset {.tabset}

```{r message = F, warning = F, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, fig.path = 'figs/')

library(tidyverse)
library(sf)
library(mapview)
library(patchwork)
library(lubridate)
library(ggrepel)
library(Cprob)

prj <- 4326 # wgs84

source('R/funcs.R')

pbase <- theme_bw(base_family = 'serif', base_size = 14) +
  theme(
    strip.background = element_blank(), 
    legend.position = 'top', 
    legend.title = element_blank()
  )

data(wqdat)

# all wq data as sf
wqdatgeo <- wqdat %>% 
  filter(!is.na(Lat)) %>% 
  st_as_sf(., coords = c('Long', 'Lat'), crs = prj)

# caron dataset
jsdat <- wqdat %>% 
  select(Year, Month, `Full Date`, `Project ID`, `Station ID`, Depth, `Depth Category`, `Lat`, `Long`, `DA (ng/mL)`, `PN cells (cells/L)`, `Chl a (ug/L)`, Temp, Salinity, `NO2+NO3`) %>% 
  filter(grepl('^Schnetzer|^ECOHAB|^B08|^SCCOOS|^OCSC', `Project ID`)) %>% 
  filter(!grepl('^Santa\\sMonica\\sPier|^Newport', `Station ID`)) %>% 
  filter(Long > -118.83 & Long < -117.7) %>% 
  filter(!is.na(Lat)) %>% 
  rename(
    chla = `Chl a (ug/L)`,
    da = `DA (ng/mL)`,
    pn = `PN cells (cells/L)`,
    temp = Temp, 
    sal = Salinity, 
    nitrogen = `NO2+NO3`
  ) %>% 
  st_as_sf(., coords = c('Long', 'Lat'), crs = prj)

# newport and santa monica ts
tsdat <- wqdat %>% 
  select(Year, Month, `Full Date`, `Project ID`, `Station ID`, Depth, `Depth Category`, `Lat`, `Long`, `DA (ng/mL)`, `PN cells (cells/L)`, `Chl a (ug/L)`, Temp, Salinity, `NO2+NO3`) %>% 
  filter(grepl('^Santa\\sMonica\\sPier|^Newport', `Station ID`)) %>% 
  rename(
    chla = `Chl a (ug/L)`,
    da = `DA (ng/mL)`,
    pn = `PN cells (cells/L)`,
    temp = Temp, 
    sal = Salinity, 
    nitrogen = `NO2+NO3`
  ) %>% 
  filter(!is.na(Lat)) %>% 
  st_as_sf(., coords = c('Long', 'Lat'), crs = prj)
```

## Plots

Locations with lat/lon, summarized by numbers of years sampled:
```{r}
wqdatgeosum <- wqdat %>% 
  filter(!is.na(Lat)) %>%
  group_by(`Station ID`) %>% 
  nest %>% 
  mutate(
    nyrs = purrr::map(data, function(x) length(unique(x$Year))),
    Lat = purrr::map(data, function(x) mean(x$Lat, na.rm = T)), 
    Long = purrr::map(data, function(x) mean(x$Long, na.rm = T))
  ) %>% 
  dplyr::select(-data) %>% 
  unnest %>% 
  st_as_sf(., coords = c('Long', 'Lat'), crs = prj)

mapview(wqdatgeosum, zcol = 'nyrs', layer.name = "Years sampled")
```

Caron dataset:
```{r}
mapview(jsdat)
```

Time series data, Newport Beach and Santa Monica Pier:
```{r, fig.height = 7, fig.width = 12}
toplo <- tsdat %>% 
  st_set_geometry(NULL) %>% 
  dplyr::select(`Full Date`, `Station ID`, da, pn, chla) %>%
  mutate(
    da = 1000*da, # mg/L
    da.edit = ifelse(da > 400, 401, da),
    text.da = ifelse(da > 400, 'Y', 'N'),
    zero.da = ifelse(da > 0, 'N', 'Y'), 
    pn = pn / 1000, # cells/ml
    pn.edit = ifelse(pn > 400, 401, pn),
    text.pn = ifelse(pn > 400, 'Y', 'N'),
    zero.pn = ifelse(pn > 0, 'N', 'Y'),
    chla.edit = ifelse(chla > 20, 21, chla),
    text.chla = ifelse(chla > 20, 'Y', 'N'),
    zero.chla = ifelse(chla > 0, 'N', 'Y')
  )
dalabs <- filter(toplo, text.da == 'Y')
pnlabs <- filter(toplo, text.pn == 'Y')
chlalabs <- filter(toplo, text.chla == 'Y')

# point scales
scls <- c(1, 12)

leglab <- expression(paste('conc. (ng ', mL^-1, ')'))
brks <- c(0, 50, 100, 150, 200, 400)
labs <- c('>0-50', '50-100', '100-150', '150-200', '200-400', '>400')
p1 <- ggplot(toplo, aes(x = `Full Date`, y = `Station ID`)) + 
  geom_point(aes(size = da.edit, shape = zero.da, colour = da.edit), alpha = 0.8) + 
  geom_label_repel(data = dalabs, aes(label = floor(da)), 
    box.padding = 1,
    point.padding = NA, 
    size = 4, alpha = 0.7, 
    min.segment.length = 0,
    colour = 'tomato1'
    ) +
  theme_bw(base_family = 'serif') + 
  theme(axis.title = element_blank()) +
  scale_size_continuous(leglab,
    breaks = brks,
    range = scls, 
    labels = labs
    ) + 
  scale_colour_gradientn(leglab, 
    element_text('test'),
    colours = c('gray50', 'grey15'),
    breaks = brks,
    labels = labs
    ) + 
  scale_shape_manual(values = c(16, 1), guide = F) +
  guides(colour = guide_legend(), size = guide_legend()) +
  ggtitle('(a) Domoic Acid (DA)') 

leglab <- expression(paste('cells (', L^-1, ')'))
brks <- c(0, 50, 100, 150, 200, 400)
labs <- c('>0-50', '50-100', '100-150', '150-200', '200-400', '>400')
p2 <- ggplot(toplo, aes(x = `Full Date`, y = `Station ID`)) + 
  geom_point(aes(size = pn.edit, shape = zero.pn, colour = pn.edit), alpha = 0.8) + 
  geom_label_repel(data = pnlabs, aes(label = floor(pn)), 
    box.padding = 1,
    point.padding = NA, 
    size = 4, alpha = 0.7, 
    min.segment.length = 0,
    colour = 'tomato1'
    ) +
  theme_bw(base_family = 'serif') + 
  theme(axis.title = element_blank()) +
    scale_size_continuous(leglab,
    breaks = brks,
    range = scls, 
    labels = labs
    ) + 
  scale_colour_gradientn(leglab, 
    element_text('test'),
    colours = c('gray50', 'grey15'),
    breaks = brks,
    labels = labs
    ) + 
  scale_shape_manual(values = c(16, 1), guide = F) +
  guides(colour = guide_legend(), size = guide_legend()) +
  ggtitle('(b) Pseudo-nitzschia') 

leglab <- expression(paste('conc. (ug ', L^-1, ')'))
brks <- c(0, 1, 5, 10, 15, 20)
labs <- c('>0-1', '1-5', '5-10', '10-15', '15-20', '>20')
p3 <- ggplot(toplo, aes(x = `Full Date`, y = `Station ID`)) + 
  geom_point(aes(size = chla.edit, shape = zero.chla, colour = chla.edit), alpha = 0.8) + 
  geom_label_repel(data = chlalabs, aes(label = floor(chla)), 
    box.padding = 1,
    point.padding = NA, 
    size = 4, alpha = 0.7, 
    min.segment.length = 0,
    colour = 'tomato1'
    ) +
  theme_bw(base_family = 'serif') + 
  theme(axis.title = element_blank()) +
    scale_size_continuous(leglab,
    breaks = brks,
    range = scls, 
    labels = labs
    ) + 
  scale_colour_gradientn(leglab, 
    element_text('test'),
    colours = c('gray50', 'grey15'),
    breaks = brks,
    labels = labs
    ) + 
  scale_shape_manual(values = c(16, 1), guide = F) +
  guides(colour = guide_legend(), size = guide_legend()) +
  ggtitle('(c) Chlorophyll-a') 

p1 + p2 + p3 + plot_layout(ncol = 1)
```

Logistic regression of likelihood of seeing DA with chl, all Bight stations:
```{r, eval = T, fig.height = 4, fig.width = 9}

toplo1 <- jsdat %>% 
  mutate(
    dapa = ifelse(da > 0, 1, 0)
  ) %>% 
  filter(!is.na(chla) & !is.na(da))

leglab <- expression(paste('Domoic acid\nconc. (ng ', L^-1, ')'))

p1 <- ggplot(toplo1, aes(x = chla, y = dapa)) + 
  geom_point(aes(size = da), alpha = 0.7) + 
  theme_bw(base_family = 'serif') + 
  geom_smooth(method = "glm", method.args = list(family = "binomial"), colour = 'black') +
  scale_x_log10(expression(paste('Chl-a (ug ', L^-1, ')'))) + 
  ylab('Likelihood of Domoic acid') + 
  scale_size_continuous(leglab, range = c(1, 8))

toplo2 <- jsdat %>% 
  filter(!is.na(chla) & !is.na(pn)) %>% 
  mutate(
    pnhilo = ifelse(pn > 10, 1, 0)
  ) 

leglab <- expression(paste('Cells (', L^-1, ')'))

p2 <- ggplot(toplo2, aes(x = chla, y = pnhilo)) + 
  geom_point(aes(size = pn), alpha = 0.7) + 
  theme_bw(base_family = 'serif') + 
  geom_smooth(method = "glm", method.args = list(family = "binomial"), colour = 'black') +
  scale_x_log10(expression(paste('Chl-a (ug ', L^-1, ')'))) + 
  scale_y_continuous(expression(paste('Likelihood of high cell concentration (> 10    ', L^-1, ')'))) + 
  scale_size_continuous(leglab, range = c(1, 8))

p1 + p2 + plot_layout(ncol = 2)
```

Conditional probability plots:
```{r, eval = F}
data(mgus)
mgus$A <- ifelse(mgus$age < 64, 0, 1)

fit <- cpf(Hist(time, ev)~A, mgus)

plot(fit, curvlab = c("Age < 64", "Age >= 64"),
     main = "Conditional Probability of Cancer", xlab = "Years")

toplo1 <- jsdat %>% 
  mutate(
    dapa = ifelse(da > 0, 1, 0),
    dapa = as.integer(dapa)
  ) %>% 
  filter(!is.na(chla) & !is.na(da)) %>% 
  st_set_geometry(NULL) %>% 
  dplyr::select(dapa, da, chla)


cpf(Hist(chla, da), toplo1)
mod <- prodlim(Hist(chla, dapa) ~ 1, toplo1)
```

